title = "Blot BOM"

notes = """
What cable does the stepper motor use?

CA will make box.
Specify how much room we need in the box.

Add picture of all parts

Philips head for adjusting pot?
"""

[schema]
part = "string"
quantity = "number"
exampleSource = "link"
findLocalSupplier = "boolean"
notes = "string"
image = "image"
container = ["box #1", "box #2", "box #3", "box #4", "electronics box", "free floating", "small parts bag", "tool bundle"]
tags = ["tool", "3d-Printer", "laser cut", "circuit"]
# designFiles = ["stl", "dxf", "gerber + bom"]
itemId = "uuid" # to identify the part

[[items]]
part = "3mm allen key"
notes = "for tightening most screws"
exampleSource = "https://www.mcmaster.com/7289A14"
quantity = 1
findLocalSupplier = true
tags = ["tool"]
container = "tool bundle"

[[items]]
part = "2.5mm allen key"
notes = "for attaching stepper motors"
exampleSource = "https://www.mcmaster.com/7289A13"
quantity = 1
findLocalSupplier = true
tags = ["tool"]
container = "tool bundle"

[[items]]
part = "2mm allen key"
notes = "for tightening gears on stepper motors"
exampleSource = "https://www.mcmaster.com/7289A12"
quantity = 1
findLocalSupplier = true
tags = ["tool"]
container = "tool bundle"

[[items]]
part = "10mm wrench"
notes = "for adjusting eccentric nuts"
exampleSource = "https://www.amazon.com/TEKTON-18277-Combination-Wrench/dp/B01F510Q2U?th=1"
quantity = 1
findLocalSupplier = true
tags = ["tool"]
container = "tool bundle"

[[items]]
part = "M5x35 Button Cap Screw"
notes = "for attaching wheels to carriage"
exampleSource = "https://www.mcmaster.com/92095A220/"
quantity = 8
findLocalSupplier = true
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0056.png"
container = "box #1"

[[items]]
part = "M5x25 Button Cap Screw"
notes = "for attaching wheels to pen holder (3), and idlers on carriage (4)"
exampleSource = "https://www.mcmaster.com/92095A216/"
quantity = 7
findLocalSupplier = true
container = "box #1"

[[items]]
part = "M5 Nut"
exampleSource = "https://www.mcmaster.com/90591A260/"
quantity = 17
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0084.png"
findLocalSupplier = true
container = "box #4"

[[items]]
part = "M5 T-nut"
notes = "for attaching feet, belt holder, pen rail to extrusions"
exampleSource = "https://www.amazon.com/100-Pack-Aluminum-Extrusions-Profile-Accessories/dp/B07VHNGBWJ/ref=sr_1_6?dib=eyJ2IjoiMSJ9.VrGC_YfN9GS3jY03RrLqLn1Pk7fRGm7HVTgxxF7XiN1gRG9dzdIRzGEwYRielWsMH_gtV6haMa4zgkLmi4VfdtbTSuRHBxzP1UKG_SpqbVjXQcSH6MfoDGzdt9A1VI7G0Kqn2dU9X2khSz6kyg0fEKqjTQiMrREDdeoMxHUbbDlqTIItCSlp1VKpeHp7OBRxpeZYoAFpS7s1lHYm4i2LCVO2DzaX5E4FOoKq619P5Uk.va7qt_Z-CXS4bq0b2yP2gqtBEQDoNq4VznGOw2rY03M&dib_tag=se&keywords=m5+t+nut&qid=1715219352&sr=8-6"
quantity = 14
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0085.png"
findLocalSupplier = true
container = "box #4"

[[items]]
part = "M5x20, knurled cylinder head"
notes = "for holding in pen"
exampleSource = "https://www.mcmaster.com/91292A128/"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0095.png"
findLocalSupplier = true
container = "box #1"

[[items]]
part = "Timing Belt Pulley"
exampleSource = "https://www.amazon.com/gp/product/B085XLRXS1/"
quantity = 2
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0068.png"
findLocalSupplier = true
container = "box #4"

[[items]]
part = "M5x10 Button Cap Screw"
notes = "for attaching parts to alumnium extrusion"
exampleSource = "https://www.mcmaster.com/92095A208/"
quantity = 14
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0059.png"
findLocalSupplier = true
container = "box #1"

[[items]]
part = "less than .5in diameter Rubber Feet"
exampleSource = "https://www.amazon.com/gp/product/B0BFHTGKNM/"
quantity = 4
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0078.png"
findLocalSupplier = true
container = "box #4"

[[items]]
part = "M3x10 Button Cap Screw"
notes = "for attaching stepper motors to feet"
exampleSource = "https://www.mcmaster.com/91292A113/"
quantity = 8
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0057.png"
findLocalSupplier = true
container = "small parts bag"

[[items]]
part = "Carriage"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/1x_Carriage.stl"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0094.png"
tags = ["3D-printed"]
notes = "made of PLA"
findLocalSupplier = true
container = "free floating"

[[items]]
part = "1mm tall x 10mm OD x M5 inner Alumninum Spacer"
notes = "for idler assemblies"
exampleSource = "https://www.mcmaster.com/98089A375/"
quantity = 5
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0060.png"
findLocalSupplier = true
container = "small parts bag"

[[items]]
part = "Tool Head"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/1x_ToolHead.stl"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0063.png"
tags = ["3D-printed"]
notes = "made of PLA"
findLocalSupplier = true
container = "free floating"

[[items]]
part = "6mm tall x M5 inner Eccentric Spacer"
exampleSource = "https://www.amazon.com/Micro-Traders-Eccentric-Aluminium-Extrusion/dp/B09CYK9P43/"
quantity = 5
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0055.png"
findLocalSupplier = true
container = "bag #4"

[[items]]
part = "Printed Rail"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/1x_PrintedRail.stl"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0064.png"
tags = ["3D-printed"]
notes = "made of PLA"
findLocalSupplier = true
container = "free floating"

[[items]]
part = "6mm tall x 8mm OD x M5 inner Alumnium Spacer"
exampleSource = "https://www.mcmaster.com/94669A042/"
quantity = 4
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0061.png"
findLocalSupplier = true
container = "bag #4"

[[items]]
part = "Motor Leg"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/2x_Legs.stl"
quantity = 2
tags = ["3D-printed"]
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0065.png"
container = "free floating"
findLocalSupplier = true
notes = "made of PLA"

[[items]]
part = "625zz V-Wheel" # TODO: what is the dimension
exampleSource = "https://www.amazon.com/gp/product/B09CGJZYPK/"
quantity = 11
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0053.png"
findLocalSupplier = true
container = "box #3"

[[items]]
part = "125mm long GT2 Timing Belt"
quantity = 1
findLocalSupplier = true
container = "box #2"
exampleSource = "https://openbuildspartstore.com/gt2-2m-timing-belt-by-the-foot/"

[[items]]
part = "Belt Clip"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/1x_BeltClip.stl"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0066.png"
findLocalSupplier = true
tags = ["3D-printed"]
notes = "made of PLA"
container = "free floating"

[[items]]
part = "5x16x5mm flanged bearing"
exampleSource = "https://www.amazon.com/gp/product/B07Z3DXF14/"
quantity = 10
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0054.png"
findLocalSupplier = true
container = "box #2"

[[items]]
part = "PCB Mount"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/1x_PcbMount.stl"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0087.png"
findLocalSupplier = true
tags = ["3D-printed"]
notes = "made of PLA"
container = "free floating"

[[items]]
part = "20mm x 20mm (face) x 250mm (tall) Aluminum Extrusion"
quantity = 2
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0081.png"
exampleSource = "https://openbuildspartstore.com/v-slot-20x20-linear-rail/"
findLocalSupplier = true
notes = "must have this profile"
container = "free floating"

[[items]]
part = "42mm x 42mm (face) x 38mm (tall) Stepper Motor"
exampleSource = "https://www.omc-stepperonline.com/e-series-nema-17-bipolar-42ncm-59-49oz-in-1-5a-42x42x38mm-4-wires-w-1m-cable-connector-17he15-1504s"
quantity = 2
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0067.png"
findLocalSupplier = true
notes = "could also check out https://www.amazon.com/gp/product/B0B38H2ZMR/"
container = "free floating"

[[items]]
part = "20mm Stepper motor cables"
exampleSource="https://www.amazon.com/STEPPERONLINE-Stepper-Extended-Connector-Machines/dp/B0991ZMPZY/ref=sr_1_6?dib=eyJ2IjoiMSJ9.nBzHIJIe9zbpBtF6qvScFKxiVt9UhDl3tXi8-U7LtEZ3rPaPZtK70kABHDpfeK-rAHymnIXRkUDPfh0MypKrCETB1T56kuw-XOHfGRJOTLD-IStoEmrXS_R3Oj8F-t5rpwYTKWr8ZcTMUu8whVZtK7yocoDunZJnTDou0QMDM9gK9O64IM6HF3-tYwpwFPnQ0WIcH_-kQJJkkgW-z3WZb9SyA4-GzInGS298SyF_TeU.nB4Yz5XApzuIzESRWhLGDvjZwrZ0wnYY7RM8thJTcMo&dib_tag=se&keywords=stepper%2Bmotor%2Bcable&qid=1710186192&sr=8-6&th=1"
quantity = 2
findLocalSupplier = true
notes = "to connect steppers to control board; can't be too long or too short; around 24 AWG"
container = "electronics box"

[[items]]
part = "PCB - control board"
exampleSource = "https://github.com/hackclub/blot/tree/main/hardware/motor-control-board"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0086.png"
findLocalSupplier = true
notes = "manufacture in china"
tags = ["homemade", "circuit"]
container = "electronics box"

[[items]]
part = "xiao RP2040"
quantity = 1
findLocalSupplier = true
notes = "brains of the control board; purchase from Seeed Studios with header soldered on"
container = "electronics box"

[[items]]
part = "Servo (25mm cable) + arm"
exampleSource = "https://www.amazon.com/gp/product/B07L2SF3R4/"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0080.png"
findLocalSupplier = true
notes = "moves pen holder up and down; must have long enough cable (25mm) to connect to control board; also needs to have servo arm"
container = "electronics box"

[[items]]
part = "Carriage Plate"
exampleSource = "https://github.com/hackclub/blot/blob/main/hardware/mechanical/blot-v6/1x_CarriagePlate.dxf"
quantity = 1
image = "https://raw.githubusercontent.com/hackclub/blot/main/docs/AssemblyImages/Image0093.png"
findLocalSupplier = true
notes = "helps make the carriage rigid; could be manufactured by SendCutSend, 1/8 in. aluminium"
tags = ["laser cut"]
container = "free floating"

[[items]]
part = "usb-c to usb-c cable"
quantity = "2"
findLocalSupplier = true
notes = "one is for data and one is for power"
container = ["free floating"]
exampleSource = "https://www.amazon.com/Anker-Charger-Charge-Samsung-MacBook/dp/B0BPC6TTNX/ref=sr_1_4?crid=MFMY6EHF4YD4&dib=eyJ2IjoiMSJ9.M_O_Qv-JwLbNI5sT1Ur5uYgs1daGqR6YGwEQBckTevilVJ7IwpcrghaGDUk1AAvLz9XjADXFTEbq571L986R2i7_rd-mi1-wrgE7iZMEm-JKy58lv_NnQ2nLkiPBVOTSee1GTKWPYMqZV6Xpmy_thz-g3tjxVjAUllETPwR9p9KwgFQ4wc5RyP7CHGKa5YpKhTuPYtlvuaU6IvBoRPHPBBpNFuSgYS6lffh8yHOCaCCfVgJaGstQ1sTzIrsmu2Q6HAuKZ0p3fWymPJSDdBLF2mRd8GdpeEVBJ3k8u2GRoEQ.6J7Rv3_UhICDy0ThujHeO8oSj-bL0d5mclnurCv1ts4&dib_tag=se&keywords=usb%2Bc%2Bto%2Busb%2Bc%2Bcable%2B3%2Bft&qid=1709320007&s=industrial&sprefix=usb%2Bc%2Bto%2Busb%2Bc%2Bcable%2B3%2Bft%2Cindustrial%2C128&sr=1-4&th=1"
tags = []

[[items]]
part = "usb-c charger (brick)"
quantity = "1"
findLocalSupplier = true
notes = "30w+ is ideal, but anything over 20w can still work"
container = ["free floating"]
exampleSource = "https://www.amazon.com/3-Pack-Wall-Charger-Type-Power/dp/B0CDWLK1NG/ref=sr_1_1_sspa?crid=29EGJIM7AE9SM&dib=eyJ2IjoiMSJ9.7ou9qnO76ifgV04Xj_sOkRLlL5pgUeb2SXTmbVh4HI_RBEBJpHBs8_B256KEpt_-2w69DNolOk3PLMJ9yNNE9Rntw53xCLShXaGKb0Ob1mdRCLkfslrMzkvpkUOfqRkY05HG8cljbJ9wk8JWxCzr-GJtEZT6FZm60W1YA3_JL5r8EVmNaC_be1NG4aBJP-nA5L1-EhdPVk7YQ905Jzl_D7TVt9a4VQFHSMHI-tMTiTQIfhZxg1jxE4l21OM_RfDGWsdOTkPAY-xhoBYSuduejvXXOGN9EXybJzlPefaX3nM.MvMmBQ3YMB5EYjF-qFkQpaKqir0M-9hAG5VWGLFHFdU&dib_tag=se&keywords=20w+usb-c&qid=1709663916&s=industrial&sprefix=20w+usb-c%2Cindustrial%2C125&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1&smid=A3T7NGXH3L1OEM"
tags = []
